services:
  gateway:
    build: .
    environment:
      - PORT=4000
      - REDIS=redis:6379
    ports:
      - 4000:4000
    volumes:
      - ./src:/web/src
      - ./schemas:/web/schemas
    depends_on:
      - redis
    command: yarn dev
  redis:
    image: redis:6-alpine
    ports:
      - "6379:6379"
